spring:
  cloud:
    function:
      definition: comment; like; follow;
    stream:
      binder:
        brokers: localhost:9092
      bindings:
        comment-in-0:
          destination: comment # destination는 kafka 토픽 이름
          content-type: application/json
          group: notification-consumer
          consumer.max-attempts: 2
        like-in-0:
          destination: like
          content-type: application/json
          group: notification-consumer
          consumer.max-attempts: 2
        follow-in-0:
          destination: follow
          content-type: application/json
          group: notification-consumer
          consumer.max-attempts: 2